version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Vienna"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Vienna"
    groups:
      nuke:
        patterns:
          - "Nuke*"
      mstest:
        patterns:
          - "MSTest*"
      nunit:
        patterns:
          - "NUnit*"
      tunit:
        patterns:
          - "tunit*"
      xunit:
        patterns:
          - "xunit*"
